### ISSUE TITLE
[docs] Issue with 'Require charset meta tag with the value of `utf-8`'

### ISSUE THREAD

**Issue by scheinercc** [sonarwhal/sonar#611] opened 2017-10-29 05:35 UTC
https://sonarwhal.com/docs/user-guide/rules/meta-charset-utf-8/index.html

Not sure if this is the right place for a possible issue with the test.

Fairly sure that I fulfill all the requirements here, only problem for the tester might be this (slightly outdated) code block
```
<!--[if lte IE 7]> <html class="no-js lt-ie8" lang="en"> <![endif]-->
<!--[if lte IE 9]> <html class="no-js lt-ie10" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
```

link: http://scheiner.cc/

**Comment by alrra** [comment] 2017-10-29 08:12
> Not sure if this is the right place for a possible issue with the test.

Yes, this is the right place.

>  'Require charset meta tag with the value of `utf-8`'
>
> Fairly sure that I fulfill all the requirements here, 

@scheinercc  **But you do pass that rule.** I don't see the error anywhere, and I tested using both the CLI and the online scanner (see: https://sonarwhal.com/scanner/97de3f8a-e08e-4e0a-8fc5-cde508166e44).

> only problem for the tester might be this (slightly outdated) code block
>
> ```
> 
> 
>  <html class="no-js" lang="en"> 
> ```

That part shouldn't have any impact on the `meta-charset-utf-8` rule.

---

@scheinercc I'm going to close this as everything seems to work as intended, but I'm happy to reopen it if you provide more details that can help show any problems.

**Closed by alrra** 2017-10-29 08:12 UTC

**Comment by scheinercc** [comment] 2017-10-29 11:20
@alrra interesting, I can found it on my first test run:
https://sonarwhal.com/scanner/24673c0c-6d7e-49e3-a957-b14e5639f7eb

**Comment by scheinercc** [comment] 2017-10-29 11:23
@alrra - all good. Ran the test again and it's not showing anymore :)
https://sonarwhal.com/scanner/0a4069b0-ec11-4b0e-8793-86202942e1d2

**Comment by molant** [comment] 2017-10-29 11:26
If you expand the results of any rule in that scan run you'll see that it says:

> Error in sonar analyzing this rule

That means we had some internal problem to run the rule at that moment and we couldn't get any result.
