### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by jigneshdpatel** [sonarwhal/sonar#304] opened 2017-06-22 16:21 UTC
I installed sonar as indicated on the website and getting following error. Am I missing something?

C:\>sonar https://sonarwhal.com/
C:\Users\jignesh\AppData\Roaming\npm\node_modules\@sonarwhal\sonar\dist\src\bin\sonar.js:27
const run = async () => {
                  ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by austinkelleher** [comment] 2017-06-22 16:22
Duplicate of https://github.com/sonarwhal/sonar/issues/299. We should be more clear about the current Node.js 8 limitation.

**Closed by austinkelleher** 2017-06-22 16:22 UTC

**Comment by molant** [comment] 2017-06-22 16:39
Yes, changes are already live in the site:

![image](https://user-images.githubusercontent.com/606594/27445459-a70947ee-572e-11e7-8b61-3202d60263ec.png)

![image](https://user-images.githubusercontent.com/606594/27445466-b07d840c-572e-11e7-87f6-a6145e7c4238.png)

**Comment by jonathansampson** [comment] 2017-09-13 19:49
@molant Did the website regress? This is what I see on the homepage:

![image](https://user-images.githubusercontent.com/815158/30397461-9dfbfdf4-9892-11e7-8678-8621268a3090.png)

**Comment by molant** [comment] 2017-09-13 21:47
@jonathansampson the installation of node 8 should be covered [with this](https://github.com/sonarwhal/sonar/blob/a0c52062a5205ab7c7537178982d53e76823137f/package.json#L120) but it looks like it [is not working](https://github.com/sonarwhal/sonar/issues/511) :/

**Comment by jonathansampson** [comment] 2017-09-13 21:59
@molant Yeah, I saw your comment about package.json covering the requirement. I don't have Node 8 installed, but I also don't recall seeing any warnings. As stated in that issue, Sonar installed straightaway. Glad to see an issue captured. Looking forward to playing with Sonar!
