### ISSUE TITLE
`meta-charset-utf-8` and BOM

### ISSUE THREAD

**Issue by tigt** [sonarwhal/sonar#328] opened 2017-06-27 16:32 UTC
Some HTML minifiers replace `<meta charset="utf-8">` with a Byte-Order Mark at the beginning of the file, [which has the same effect in browsers](https://www.w3.org/TR/html5/syntax.html#determining-the-character-encoding).

Should the rule pass in this case? I feel that it should.

**Comment by alrra** [comment] 2017-06-27 17:01
> Some HTML minifiers

@tigt Can you give some examples? Thanks!

**Comment by alrra** [comment] 2017-07-03 09:15
When I did the rule, I thought a little bit about this case, but decided against making the rule pass because of it. In my opinion, relying on BOM is the kind of thing that has the potential to create more problems:

   * Some tools/build processes will strip the BOM character (just look how used tools like [this one]( https://www.npmjs.com/package/strip-bom) is), which will mean a lot of figuring out where the problem is.
   * Most people probably don't know about BOM, and will be confused about the weird character their editor **may** show.
   * [+ other (old?) issues](https://www.w3.org/International/questions/qa-byte-order-mark#problems)

----

I'm going to close this for now, but I'm happy to reopen it and continue the discussion if you provide more concrete examples.

**Closed by alrra** 2017-07-03 09:15 UTC
Labels: area:rule, awaiting feedback

**Comment by tigt** [comment] 2017-07-03 20:08
That's fair reasoning. Should I work on rules that specifically note when the BOM is present but `<meta charset>` isn't?

**Comment by alrra** [comment] 2017-07-04 07:56
> that specifically note when the BOM is present but `<meta charset>` isn't?

@tigt Can you be more specific? I do apologize, but I don't quite understand what you're proposing.

**Comment by tigt** [comment] 2017-07-09 00:03
I misspoke. Should Sonar warn if the BOM is present, for the reasons you described?

**Comment by alrra** [comment] 2017-07-09 07:10
> warn if the BOM is present

@tigt Wanna open a new issue, and propose a new rule for that? Thanks!
